/* ==========================================================================
   Stackly — Shared product catalog & render helpers
   Used by shop.html, product.html and index.html
   ========================================================================== */
(function () {
  "use strict";

  const PRODUCTS = [
    {
      id: 1,
      name: "Glow Renewal Serum",
      category: "serum",
      catLabel: "Serum",
      price: 42,
      oldPrice: 52,
      rating: 4.9,
      reviews: 214,
      badge: "new",
      concern: "brightening",
      img: "images/photo-1679394270597-e90694d70350.webp",
      short: "A weightless glow-boosting serum with vitamin B3 and bakuchiol.",
      long: "Our cult-favourite Glow Renewal Serum pairs 5% niacinamide with antioxidant-rich bakuchiol to visibly even tone, smooth texture and restore a lit-from-within radiance. Absorbs in seconds — zero stickiness, zero fragrance overload.",
      ingredients: ["Niacinamide 5%", "Bakuchiol", "Hyaluronic Acid", "Green Tea Extract", "Squalane"],
      sizes: ["30ml", "50ml"],
    },
    {
      id: 2,
      name: "Hydra-Dew Cream",
      category: "moisturizer",
      catLabel: "Moisturizer",
      price: 36,
      oldPrice: null,
      rating: 4.8,
      reviews: 167,
      badge: "hot",
      concern: "hydration",
      img: "images/photo-1665763630810-e6251bdd392d.webp",
      short: "A cloud-light gel-cream that floods skin with 72h hydration.",
      long: "Hydra-Dew Cream delivers multi-weight hyaluronic acid and ceramides in a whipped, cloud-like texture. It melts into skin to plump, soothe and lock in moisture for up to 72 hours — day or night.",
      ingredients: ["Ceramides NP", "Pentavitin", "Hyaluronic Acid", "Glycerin", "Aloe Vera"],
      sizes: ["50ml", "100ml"],
    },
    {
      id: 3,
      name: "Botanic Repair Oil",
      category: "oil",
      catLabel: "Facial Oil",
      price: 48,
      oldPrice: 60,
      rating: 5.0,
      reviews: 98,
      badge: "sale",
      concern: "repair",
      img: "images/photo-1767102125499-0ce314436f67.webp",
      short: "A nourishing botanical blend that repairs the moisture barrier overnight.",
      long: "Botanic Repair Oil is a dry-touch blend of rosehip, marula and camellia oils that works while you sleep. It seals in actives, calms irritation and leaves a soft, dewy finish — never greasy.",
      ingredients: ["Rosehip Oil", "Marula Oil", "Camellia Oil", "Squalane", "Vitamin E"],
      sizes: ["30ml"],
    },
    {
      id: 4,
      name: "Velvet Sun Shield SPF50",
      category: "sun",
      catLabel: "Sun Care",
      price: 29,
      oldPrice: null,
      rating: 4.7,
      reviews: 132,
      badge: null,
      concern: "protection",
      img: "images/photo-1775989982439-610be22c8c7b.webp",
      short: "An invisible, velvety SPF50 that doubles as a makeup-perfecting primer.",
      long: "Velvet Sun Shield delivers broad-spectrum SPF50 with a silky, blurring finish that sits beautifully under makeup. Fragrance-free, non-greasy and reef-safe.",
      ingredients: ["Zinc Oxide 18%", "Ceramide NP", "Glycerin", "Vitamin E"],
      sizes: ["40ml"],
    },
    {
      id: 5,
      name: "Vitamin C Brighten Serum",
      category: "serum",
      catLabel: "Serum",
      price: 39,
      oldPrice: null,
      rating: 4.9,
      reviews: 256,
      badge: "hot",
      concern: "brightening",
      img: "images/photo-1723951174326-2a97221d3b7f.webp",
      short: "Stable 15% vitamin C to fade dark spots and boost antioxidant defence.",
      long: "Stabilised 15% ascorbyl glucoside brightens dullness and fades post-acne marks without irritation. Our slow-release encapsulation keeps it active — and kind — even on sensitive skin.",
      ingredients: ["15% Vitamin C", "Ferulic Acid", "Tranexamic Acid", "Hyaluronic Acid"],
      sizes: ["30ml"],
    },
    {
      id: 6,
      name: "Cloud Quench Gel",
      category: "moisturizer",
      catLabel: "Moisturizer",
      price: 32,
      oldPrice: null,
      rating: 4.6,
      reviews: 89,
      badge: null,
      concern: "hydration",
      img: "images/photo-1640625696922-1fd63c0b97c9.webp",
      short: "A featherlight gel moisturiser for oily and combination skin.",
      long: "Cloud Quench Gel swaps heavy butters for a breathable, water-gel formula. Green tea and niacinamide control shine while polyglutamic acid keeps skin plump without clogging pores.",
      ingredients: ["Polyglutamic Acid", "Niacinamide", "Green Tea Extract", "Hyaluronic Acid"],
      sizes: ["50ml"],
    },
    {
      id: 7,
      name: "Midnight Recovery Drops",
      category: "oil",
      catLabel: "Facial Oil",
      price: 44,
      oldPrice: null,
      rating: 4.8,
      reviews: 76,
      badge: "new",
      concern: "repair",
      img: "images/photo-1702475139570-b90434243af2.webp",
      short: "An overnight retinoid alternative that renews while you rest.",
      long: "Midnight Recovery Drops combine plant-derived bakuchiol, sea buckthorn and squalane to resurface and renew overnight. Wake up to smoother, brighter, calmer skin — no irritation, no sun sensitivity.",
      ingredients: ["Bakuchiol", "Sea Buckthorn", "Squalane", "Grape Seed Oil"],
      sizes: ["30ml"],
    },
    {
      id: 8,
      name: "Mineral Glow Tint SPF30",
      category: "sun",
      catLabel: "Sun Care",
      price: 34,
      oldPrice: null,
      rating: 4.5,
      reviews: 58,
      badge: null,
      concern: "protection",
      img: "images/photo-1745159338135-39f6b462b382.webp",
      short: "A sheer mineral tint with SPF30 that gives skin a healthy glow.",
      long: "One product, three jobs: sun protection, light coverage and glow. Mineral Glow Tint evens tone with a soft-focus finish while mineral filters defend against UVA/UVB.",
      ingredients: ["Zinc Oxide 12%", "Iron Oxides", "Hyaluronic Acid", "Vitamin E"],
      sizes: ["35ml"],
    },
    {
      id: 9,
      name: "Barrier Repair Essence",
      category: "serum",
      catLabel: "Serum",
      price: 46,
      oldPrice: null,
      rating: 4.9,
      reviews: 121,
      badge: null,
      concern: "repair",
      img: "images/photo-1596462502278-27bfdc403348.webp",
      short: "A hydrating essence that rebuilds a compromised skin barrier.",
      long: "Barrier Repair Essence is the first step after cleansing — a fermented rice-and-peptide essence that rebalances pH, calms redness and preps skin to absorb everything that follows.",
      ingredients: ["Fermented Rice Water", "Peptides", "Panthenol", "Beta-Glucan"],
      sizes: ["120ml"],
    },
    {
      id: 10,
      name: "Ceramide Soufflé Cream",
      category: "moisturizer",
      catLabel: "Moisturizer",
      price: 38,
      oldPrice: null,
      rating: 4.7,
      reviews: 143,
      badge: "hot",
      concern: "hydration",
      img: "images/photo-1772023042063-ef4ae9bc6d39.webp",
      short: "A whipped ceramide cream for very dry, sensitive skin.",
      long: "A fluffy soufflé of five ceramides, shea butter and colloidal oat that calms itching, flakiness and sensitivity. Dermatologist-approved for eczema-prone skin.",
      ingredients: ["5-Ceramide Complex", "Colloidal Oat", "Shea Butter", "Centella Asiatica"],
      sizes: ["50ml", "100ml"],
    },
    {
      id: 11,
      name: "Rosehip Glow Oil",
      category: "oil",
      catLabel: "Facial Oil",
      price: 41,
      oldPrice: null,
      rating: 4.6,
      reviews: 64,
      badge: null,
      concern: "brightening",
      img: "images/photo-1643379850274-77d2e3703ef9.webp",
      short: "Cold-pressed rosehip oil that softens scars and revives dull skin.",
      long: "Single-ingredient, cold-pressed, organic rosehip oil — rich in vitamin A and omega-3s to fade scars, smooth fine lines and restore a dewy, healthy glow.",
      ingredients: ["Organic Rosehip Seed Oil 100%"],
      sizes: ["30ml"],
    },
    {
      id: 12,
      name: "Every-Skin Daily SPF",
      category: "sun",
      catLabel: "Sun Care",
      price: 27,
      oldPrice: null,
      rating: 4.6,
      reviews: 205,
      badge: null,
      concern: "protection",
      img: "images/photo-1767256046031-743d33937c4e.webp",
      short: "The everyday SPF30 that works for every skin tone, minus white cast.",
      long: "A transparent, fast-absorbing SPF30 for all skin types and tones. No white cast, no pilling — just reliable daily defence that makes SPF a habit you'll actually keep.",
      ingredients: ["Zinc Oxide 10%", "Niacinamide", "Glycerin"],
      sizes: ["50ml"],
    },
    {
      id: 13,
      name: "Foaming Cream Cleanser",
      category: "cleanser",
      catLabel: "Cleanser",
      price: 24,
      oldPrice: null,
      rating: 4.8,
      reviews: 189,
      badge: "hot",
      concern: "hydration",
      img: "images/photo-1556228720-195a672e8a03.webp",
      short: "A gentle milky foam that melts away makeup without stripping skin.",
      long: "A pH-balanced cream-to-foam cleanser that lifts away SPF, makeup and grime while amino acid surfactants keep the moisture barrier intact. No tightness, no squeak — just clean, calm skin.",
      ingredients: ["Amino Acid Surfactants", "Ceramide NP", "Panthenol", "Glycerin"],
      sizes: ["150ml"],
    },
    {
      id: 14,
      name: "Pure Gel Cleanser",
      category: "cleanser",
      catLabel: "Cleanser",
      price: 22,
      oldPrice: null,
      rating: 4.6,
      reviews: 143,
      badge: null,
      concern: "brightening",
      img: "images/photo-1570172619644-dfd03ed5d881.webp",
      short: "A clarifying gel wash with salicylic acid for congestion-prone skin.",
      long: "Pure Gel Cleanser pairs 1.5% BHA with green tea to sweep away oil, dead cells and congestion. The silky gel lathers lightly and rinses clean — ideal for oily and combination skins.",
      ingredients: ["Salicylic Acid 1.5%", "Green Tea Extract", "Zinc PCA", "Aloe Vera"],
      sizes: ["200ml"],
    },
    {
      id: 15,
      name: "Clarifying Clay Mask",
      category: "mask",
      catLabel: "Mask",
      price: 30,
      oldPrice: 36,
      rating: 4.7,
      reviews: 97,
      badge: "sale",
      concern: "repair",
      img: "images/photo-1585232004423-244e0e6904e3.webp",
      short: "A 10-minute kaolin clay mask that detoxifies without over-drying.",
      long: "Clarifying Clay Mask draws out impurities with pink kaolin while ceramides and oat calm the skin afterwards. Twice a week, pores look smaller and skin feels refreshed — never tight.",
      ingredients: ["Pink Kaolin Clay", "Zinc Oxide", "Colloidal Oat", "Centella Asiatica"],
      sizes: ["75ml"],
    },
    {
      id: 16,
      name: "Hydra-Burst Sheet Mask Duo",
      category: "mask",
      catLabel: "Mask",
      price: 18,
      oldPrice: null,
      rating: 4.5,
      reviews: 210,
      badge: "new",
      concern: "hydration",
      img: "images/photo-1556228453-efd6c1ff04f6.webp",
      short: "Two eco-cotton sheet masks soaked in a ceramide-hyaluronic cocktail.",
      long: "Each sheet mask floods skin with triple-weight hyaluronic acid and ceramides for an instant dewy quench. Sustainable cotton fibres, bio-cellulose fit, and enough serum to give your neck some love too.",
      ingredients: ["Triple Hyaluronic Acid", "Ceramide NP", "Betaine", "Allantoin"],
      sizes: ["2 × 25ml"],
    },
    {
      id: 17,
      name: "Lift & Bright Eye Cream",
      category: "eye",
      catLabel: "Eye Care",
      price: 35,
      oldPrice: null,
      rating: 4.8,
      reviews: 128,
      badge: "hot",
      concern: "brightening",
      img: "images/photo-1612817288484-6f916006741a.webp",
      short: "A caffeine-peptide eye cream that de-puffs and brightens dark circles.",
      long: "Lift & Bright Eye Cream combines 5% caffeine, peptides and vitamin C to visibly reduce puffiness and dark circles. The cooling metal applicator glides on and instantly wakes up tired eyes.",
      ingredients: ["Caffeine 5%", "Peptide Complex", "Vitamin C", "Hyaluronic Acid"],
      sizes: ["15ml"],
    },
    {
      id: 18,
      name: "Caffeine Dew Eye Serum",
      category: "eye",
      catLabel: "Eye Care",
      price: 28,
      oldPrice: null,
      rating: 4.6,
      reviews: 84,
      badge: null,
      concern: "repair",
      img: "images/photo-1598440947619-2c35fc9aa908.webp",
      short: "A featherlight eye serum that firms and smooths fine lines.",
      long: "A breathable gel serum with caffeine, squalane and rosehip that firms the eye contour while you sleep. Layers beautifully under concealer and never creases or pills.",
      ingredients: ["Caffeine", "Squalane", "Rosehip Oil", "Arnica"],
      sizes: ["15ml"],
    },
    {
      id: 19,
      name: "Tranexamic Spot Corrector",
      category: "serum",
      catLabel: "Serum",
      price: 40,
      oldPrice: null,
      rating: 4.7,
      reviews: 152,
      badge: null,
      concern: "brightening",
      img: "images/photo-1620916566398-39f1143ab7be.webp",
      short: "A targeted dark-spot serum that visibly fades stubborn pigmentation.",
      long: "Tranexamic acid, alpha-arbutin and licorice root work in synergy to fade sun spots, melasma and post-acne marks. Lightweight and layerable, it targets spots without bleaching surrounding skin.",
      ingredients: ["Tranexamic Acid 3%", "Alpha-Arbutin", "Licorice Root", "Niacinamide"],
      sizes: ["30ml"],
    },
    {
      id: 20,
      name: "Peptide Plump Moisturizer",
      category: "moisturizer",
      catLabel: "Moisturizer",
      price: 45,
      oldPrice: 55,
      rating: 4.9,
      reviews: 176,
      badge: "sale",
      concern: "repair",
      img: "images/photo-1702475139136-e0e376b9b8f2.webp",
      short: "A peptide-rich cream that plumps lines and rebuilds elasticity.",
      long: "Eight peptides, squalane and ceramides work together to visibly plump fine lines and firm sagging contours. Rich yet fast-absorbing, it's the last step your skin wants at night.",
      ingredients: ["8-Peptide Complex", "Squalane", "Ceramide NP", "Shea Butter"],
      sizes: ["50ml", "100ml"],
    },
    {
      id: 21,
      name: "Ultra-Rich Body Butter",
      category: "moisturizer",
      catLabel: "Moisturizer",
      price: 26,
      oldPrice: null,
      rating: 4.8,
      reviews: 232,
      badge: null,
      concern: "hydration",
      img: "images/photo-1715750968540-841103c78d47.webp",
      short: "A whipped shea-and-cocoa body butter for parched, wintery skin.",
      long: "A decadent, quick-melting body butter whipped with raw shea, cocoa and squalane. It locks in moisture for 48 hours and leaves skin satiny, not sticky — head-to-toe indulgence.",
      ingredients: ["Raw Shea Butter", "Cocoa Butter", "Squalane", "Vitamin E"],
      sizes: ["200ml"],
    },
    {
      id: 22,
      name: "Squalane Repair Oil",
      category: "oil",
      catLabel: "Facial Oil",
      price: 37,
      oldPrice: null,
      rating: 4.7,
      reviews: 91,
      badge: null,
      concern: "repair",
      img: "images/photo-1768235146551-2a438a81aea2.webp",
      short: "A squalane-rosehip fusion that heals and shields stressed skin.",
      long: "Sugar-derived squalane and cold-pressed rosehip create a fast-absorbing oil that repairs the barrier and shields against environmental stress. Use alone or add 2 drops to your moisturiser.",
      ingredients: ["Squalane", "Rosehip Seed Oil", "Jojoba Oil", "Vitamin E"],
      sizes: ["30ml"],
    },
    {
      id: 23,
      name: "Invisible Gel SPF50",
      category: "sun",
      catLabel: "Sun Care",
      price: 31,
      oldPrice: null,
      rating: 4.7,
      reviews: 168,
      badge: "new",
      concern: "protection",
      img: "images/photo-1608248543803-ba4f8c70ae0b.webp",
      short: "A clear gel SPF50 that vanishes into skin — zero white cast.",
      long: "An ultralight water-gel sunscreen with SPF50 that dries instantly invisible. Hybrid filters, niacinamide and panthenol keep skin calm, protected and camera-ready all day.",
      ingredients: ["Zinc Oxide 15%", "Niacinamide", "Panthenol", "Glycerin"],
      sizes: ["50ml"],
    },
    {
      id: 24,
      name: "Balance Hydra Toner",
      category: "toner",
      catLabel: "Toner",
      price: 23,
      oldPrice: null,
      rating: 4.6,
      reviews: 119,
      badge: null,
      concern: "hydration",
      img: "images/photo-1616394584738-fc6e612e71b9.webp",
      short: "An alcohol-free essence-toner that preps and plumps in one sweep.",
      long: "A milky, alcohol-free toner with hyaluronic acid, panthenol and centella that rehydrates right after cleansing and primes skin for serums. The soft-focus finish feels like a hug in a bottle.",
      ingredients: ["Hyaluronic Acid", "Panthenol", "Centella Asiatica", "Beta-Glucan"],
      sizes: ["150ml"],
    },
    {
      id: 25,
      name: "PHA Glow Toner",
      category: "toner",
      catLabel: "Toner",
      price: 25,
      oldPrice: null,
      rating: 4.5,
      reviews: 77,
      badge: null,
      concern: "brightening",
      img: "images/photo-1512290923902-8a9f81dc236c.webp",
      short: "A gentle daily exfoliating toner that polishes skin to a glow.",
      long: "Polyhydroxy acids gently dissolve dead cells on the surface — potent enough to renew, gentle enough for daily use, even on sensitive skin. Expect smoothness, glow and smaller-looking pores.",
      ingredients: ["PHA 5%", "Hyaluronic Acid", "Green Tea Extract", "Aloe Vera"],
      sizes: ["150ml"],
    },
    {
      id: 26,
      name: "Spotless Even-Tone Serum",
      category: "serum",
      catLabel: "Serum",
      price: 43,
      oldPrice: null,
      rating: 4.8,
      reviews: 164,
      badge: null,
      concern: "brightening",
      img: "images/photo-1556228578-8c89e6adf883.webp",
      short: "A powerhouse pigment-fading serum for visibly even, luminous skin.",
      long: "Niacinamide, alpha-arbutin and vitamin C team up to fade hyperpigmentation and unify tone. Lightweight, fast-absorbing and gentle enough for daily use, morning and night.",
      ingredients: ["Niacinamide 10%", "Alpha-Arbutin", "Vitamin C", "Hyaluronic Acid"],
      sizes: ["30ml"],
    },
    {
      id: 27,
      name: "Pore-Fine BHA Serum",
      category: "serum",
      catLabel: "Serum",
      price: 33,
      oldPrice: 41,
      rating: 4.6,
      reviews: 118,
      badge: "sale",
      concern: "repair",
      img: "images/photo-1556228720-195a672e8a03.webp",
      short: "A 2% BHA treatment that visibly shrinks pores and smooths texture.",
      long: "Two percent salicylic acid dissolves the oil and debris that stretch pores, while allantoin and green tea keep skin calm. The clear, watery gel applies like a toner and absorbs fast.",
      ingredients: ["Salicylic Acid 2%", "Allantoin", "Green Tea Extract", "Niacinamide"],
      sizes: ["30ml"],
    },
    {
      id: 28,
      name: "Overnight Oat Repair Cream",
      category: "moisturizer",
      catLabel: "Moisturizer",
      price: 34,
      oldPrice: null,
      rating: 4.7,
      reviews: 139,
      badge: null,
      concern: "repair",
      img: "images/photo-1665763630810-e6251bdd392d.webp",
      short: "A colloidal-oat night cream that restores itchy, stressed skin.",
      long: "Colloidal oat, ceramides and squalane form a breathable overnight seal that calms sensitivity and rebuilds the barrier while you sleep. Wake up to skin that feels thick, calm and healthy.",
      ingredients: ["Colloidal Oat", "Ceramide NP", "Squalane", "Panthenol"],
      sizes: ["50ml"],
    },
    {
      id: 29,
      name: "Velvet Night Restore",
      category: "moisturizer",
      catLabel: "Moisturizer",
      price: 49,
      oldPrice: null,
      rating: 4.9,
      reviews: 201,
      badge: "new",
      concern: "hydration",
      img: "images/photo-1640625696922-1fd63c0b97c9.webp",
      short: "A rich overnight balm-cream that drenches dry skin in moisture.",
      long: "A silky balm-to-cream hybrid loaded with ceramides, squalane and bakuchiol that locks in moisture for a deep overnight reset. Perfect for cold climates, dry skin and long flights.",
      ingredients: ["Ceramide Complex", "Squalane", "Bakuchiol", "Shea Butter"],
      sizes: ["50ml"],
    },
    {
      id: 30,
      name: "Camellia Soft Glow Oil",
      category: "oil",
      catLabel: "Facial Oil",
      price: 39,
      oldPrice: null,
      rating: 4.6,
      reviews: 73,
      badge: null,
      concern: "hydration",
      img: "images/photo-1643379850274-77d2e3703ef9.webp",
      short: "A featherlight camellia oil that seals in glow without the grease.",
      long: "Cold-pressed camellia seed oil — rich in omega-9s and squalane — melts into skin to lock in moisture and deliver a soft, radiant finish. The perfect final step, day or night.",
      ingredients: ["Camellia Seed Oil", "Squalane", "Vitamin E"],
      sizes: ["30ml"],
    },
    {
      id: 31,
      name: "Clear-Tone Sport SPF50",
      category: "sun",
      catLabel: "Sun Care",
      price: 30,
      oldPrice: null,
      rating: 4.5,
      reviews: 66,
      badge: null,
      concern: "protection",
      img: "images/photo-1767256046031-743d33937c4e.webp",
      short: "A sweat-proof, water-resistant SPF50 for active, outdoorsy days.",
      long: "A flexible, sweat-resistant SPF50 that stays put through workouts and beach days. Mineral filters with a sheer finish, plus vitamin E to fight free radicals in the sun.",
      ingredients: ["Zinc Oxide 16%", "Vitamin E", "Glycerin"],
      sizes: ["60ml"],
    },
    {
      id: 32,
      name: "Silk Primer SPF40",
      category: "sun",
      catLabel: "Sun Care",
      price: 33,
      oldPrice: null,
      rating: 4.7,
      reviews: 154,
      badge: "hot",
      concern: "protection",
      img: "images/photo-1775989982439-610be22c8c7b.webp",
      short: "A blurring SPF40 primer that makes your foundation last longer.",
      long: "Silk Primer SPF40 smooths, blurs and mattifies while shielding skin from UVA/UVB. Silica and niacinamide keep makeup in place and shine at bay all day long.",
      ingredients: ["Zinc Oxide 14%", "Silica", "Niacinamide", "Vitamin E"],
      sizes: ["40ml"],
    },
    {
      id: 33,
      name: "Matcha Cleanse Balm",
      category: "cleanser",
      catLabel: "Cleanser",
      price: 28,
      oldPrice: 34,
      rating: 4.8,
      reviews: 187,
      badge: "sale",
      concern: "repair",
      img: "images/photo-1556228453-efd6c1ff04f6.webp",
      short: "A buttery balm cleanser that melts off makeup, even waterproof.",
      long: "A silk-melting cleansing balm infused with antioxidant matcha and camellia oil that dissolves every trace of makeup and SPF. Emulsifies to a soft milk and rinses clean — no double cleanse needed.",
      ingredients: ["Matcha Extract", "Camellia Oil", "Caprylic Triglyceride", "Vitamin E"],
      sizes: ["90ml"],
    },
    {
      id: 34,
      name: "Rosewater Balancing Toner",
      category: "toner",
      catLabel: "Toner",
      price: 20,
      oldPrice: null,
      rating: 4.4,
      reviews: 92,
      badge: null,
      concern: "hydration",
      img: "images/photo-1570172619644-dfd03ed5d881.webp",
      short: "A misty rosewater toner that refreshes and rebalances on the go.",
      long: "Distilled rosewater, witch hazel and aloe gently rebalance pH and tighten pores after cleansing. Spritz it on anytime for an instant burst of hydration and calm.",
      ingredients: ["Rosewater", "Witch Hazel", "Aloe Vera", "Glycerin"],
      sizes: ["120ml"],
    },
    {
      id: 35,
      name: "Aura Glow Peel Mask",
      category: "mask",
      catLabel: "Mask",
      price: 36,
      oldPrice: null,
      rating: 4.7,
      reviews: 88,
      badge: null,
      concern: "brightening",
      img: "images/photo-1608248543803-ba4f8c70ae0b.webp",
      short: "A 5-minute AHA peel mask that resurfaces for instant radiance.",
      long: "Glycolic and lactic acids gently lift dullness in just five minutes, while honey and oat keep skin from feeling stripped. Rinse to reveal a smooth, lit-from-within glow — no irritation.",
      ingredients: ["Glycolic Acid 8%", "Lactic Acid", "Honey", "Colloidal Oat"],
      sizes: ["75ml"],
    },
    {
      id: 36,
      name: "Firm + Lift Eye Mask Duo",
      category: "eye",
      catLabel: "Eye Care",
      price: 24,
      oldPrice: null,
      rating: 4.5,
      reviews: 57,
      badge: "new",
      concern: "repair",
      img: "images/photo-1512290923902-8a9f81dc236c.webp",
      short: "Gel eye patches that de-puff and firm while you unwind.",
      long: "Two crescent-shaped gel patches drenched in caffeine, peptides and hyaluronic acid. Leave on for 15 minutes to de-puff, brighten and firm — perfect paired with your evening wind-down.",
      ingredients: ["Caffeine", "Peptides", "Hyaluronic Acid", "Centella Asiatica"],
      sizes: ["8 pairs"],
    },
    {
      id: 37,
      name: "Probiotic Barrier Lotion",
      category: "moisturizer",
      catLabel: "Moisturizer",
      price: 29,
      oldPrice: null,
      rating: 4.6,
      reviews: 105,
      badge: null,
      concern: "repair",
      img: "images/photo-1772023042063-ef4ae9bc6d39.webp",
      short: "A probiotic lotion that balances the microbiome and calms redness.",
      long: "Lactobacillus ferment and beta-glucan fortify your skin's microbiome, while ceramides lock in hydration. A light, fast-absorbing lotion for stressed, redness-prone, city-living skin.",
      ingredients: ["Lactobacillus Ferment", "Beta-Glucan", "Ceramide NP", "Niacinamide"],
      sizes: ["100ml"],
    },
    {
      id: 38,
      name: "Radiance Morning Mist",
      category: "toner",
      catLabel: "Toner",
      price: 22,
      oldPrice: null,
      rating: 4.5,
      reviews: 83,
      badge: null,
      concern: "hydration",
      img: "images/photo-1702475139570-b90434243af2.webp",
      short: "A vitamin-infused mist that wakes skin up in seconds.",
      long: "Vitamin C, hyaluronic acid and aloe in a fine, refreshing mist. Spritz over makeup, under serum or throughout the day for a dewy, instantly-awake finish.",
      ingredients: ["Vitamin C", "Hyaluronic Acid", "Aloe Vera", "Green Tea Extract"],
      sizes: ["100ml"],
    },
    {
      id: 39,
      name: "Creamy Cleansing Milk",
      category: "cleanser",
      catLabel: "Cleanser",
      price: 21,
      oldPrice: null,
      rating: 4.6,
      reviews: 129,
      badge: null,
      concern: "hydration",
      img: "images/photo-1745159338135-39f6b462b382.webp",
      short: "A milk cleanser for dry, mature and sensitive skin.",
      long: "A creamy, no-rinse milk cleanser enriched with oat milk, squalane and allantoin. It lifts impurities while leaving skin soft and comfortable — never tight. Ideal first cleanse for dry skin.",
      ingredients: ["Oat Milk", "Squalane", "Allantoin", "Glycerin"],
      sizes: ["200ml"],
    },
    {
      id: 40,
      name: "Green Tea Purify Sheet Mask",
      category: "mask",
      catLabel: "Mask",
      price: 20,
      oldPrice: null,
      rating: 4.4,
      reviews: 71,
      badge: null,
      concern: "protection",
      img: "images/photo-1723951174326-2a97221d3b7f.webp",
      short: "A cooling green-tea mask that detoxifies and soothes angry skin.",
      long: "Antioxidant green tea, salicylic acid and aloe work together to calm breakouts and neutralise pollution stress. A 15-minute reset for congested, irritated, city-tired skin.",
      ingredients: ["Green Tea Extract", "Salicylic Acid", "Aloe Vera", "Panthenol"],
      sizes: ["5 masks"],
    },
    {
      id: 41,
      name: "Stainless Gua Sha Set",
      category: "tool",
      catLabel: "Tools",
      price: 26,
      oldPrice: null,
      rating: 4.7,
      reviews: 142,
      badge: "hot",
      concern: "repair",
      img: "images/photo-1598440947619-2c35fc9aa908.webp",
      short: "A facial massage set that de-puffs, sculpts and boosts product absorption.",
      long: "A polished stainless-steel gua sha and roller duo that glides over serum or oil to drain puffiness, sculpt cheekbones and help your skincare sink in. Gentle on sensitive skin.",
      ingredients: ["Stainless Steel", "Ergonomic Design"],
      sizes: ["2-piece set"],
    },
    {
      id: 42,
      name: "Cleansing Balm Duo",
      category: "cleanser",
      catLabel: "Cleanser",
      price: 35,
      oldPrice: null,
      rating: 4.6,
      reviews: 96,
      badge: "new",
      concern: "hydration",
      img: "images/photo-1612817288484-6f916006741a.webp",
      short: "Two travel-ready balms — calm oat and glow matcha — for your routine.",
      long: "A duo of mini cleansing balms: the Oat Calm balm soothes sensitive skin while the Matcha Glow balm melts makeup with antioxidant-rich green tea. Perfect for travel and trialling.",
      ingredients: ["Colloidal Oat", "Matcha Extract", "Camellia Oil", "Glycerin"],
      sizes: ["2 × 30ml"],
    },
    {
      id: 43,
      name: "Skincare Gift Set",
      category: "gift",
      catLabel: "Gift Set",
      price: 79,
      oldPrice: 95,
      rating: 4.9,
      reviews: 86,
      badge: "sale",
      concern: "hydration",
      img: "images/photo-1679394270597-e90694d70350.webp",
      short: "A complete ritual in a box — serum, cream and cleanser for every skin type.",
      long: "The perfect introduction to Stackly. This gift set bundles a full-size cleanser, glow serum and daily moisturizer in recyclable, gift-ready packaging — ideal for first-timers and lovers of clean beauty.",
      ingredients: ["Vitamin B3", "Hyaluronic Acid", "Ceramides", "Green Tea Extract"],
      sizes: ["3-piece set"],
    },
    {
      id: 44,
      name: "Glow & Radiance Gift Set",
      category: "gift",
      catLabel: "Gift Set",
      price: 88,
      oldPrice: 110,
      rating: 4.8,
      reviews: 74,
      badge: "sale",
      concern: "brightening",
      img: "images/photo-1608248543803-ba4f8c70ae0b.webp",
      short: "Vitamin C serum, brightening toner and a radiance mist for lit-from-within skin.",
      long: "Curated to boost luminosity, this set layers 15% vitamin C with our PHA glow toner and a fine radiance mist. Expect visibly brighter, more even skin in three weeks.",
      ingredients: ["Vitamin C 15%", "PHA 5%", "Tranexamic Acid", "Niacinamide"],
      sizes: ["3-piece set"],
    },
    {
      id: 45,
      name: "Hydration Gift Set",
      category: "gift",
      catLabel: "Gift Set",
      price: 72,
      oldPrice: 86,
      rating: 4.9,
      reviews: 121,
      badge: "sale",
      concern: "hydration",
      img: "images/photo-1598440947619-2c35fc9aa908.webp",
      short: "A drenching trio of hyaluronic toner, gel-cream and overnight balm.",
      long: "Multi-weight hyaluronic acid meets ceramides in a three-step hydration ritual. Toner preps, gel-cream quenches and the overnight balm locks everything in — up to 72 hours of moisture.",
      ingredients: ["Hyaluronic Acid", "Ceramide NP", "Squalane", "Pentavitin"],
      sizes: ["3-piece set"],
    },
    {
      id: 46,
      name: "Acne Care Gift Set",
      category: "gift",
      catLabel: "Gift Set",
      price: 65,
      oldPrice: 78,
      rating: 4.7,
      reviews: 92,
      badge: "sale",
      concern: "repair",
      img: "images/photo-1570172619644-dfd03ed5d881.webp",
      short: "BHA serum, clarifying gel wash and a pore-refining mask for clearer skin.",
      long: "A targeted kit for blemish-prone skin: salicylic-acid gel cleanser, pore-fine BHA serum and a kaolin clay mask that decongests without stripping the barrier.",
      ingredients: ["Salicylic Acid 2%", "Pink Kaolin", "Zinc PCA", "Centella Asiatica"],
      sizes: ["3-piece set"],
    },
    {
      id: 47,
      name: "Self-Care Gift Box",
      category: "gift",
      catLabel: "Gift Set",
      price: 95,
      oldPrice: 118,
      rating: 5.0,
      reviews: 58,
      badge: "sale",
      concern: "hydration",
      img: "images/photo-1596462502278-27bfdc403348.webp",
      short: "A pampering box of sheet masks, gua sha, oil and body butter.",
      long: "The ultimate wind-down bundle: hydrating sheet masks, a stainless gua sha, rosehip glow oil and whipped body butter. Everything needed for a full spa evening at home.",
      ingredients: ["Rosehip Oil", "Shea Butter", "Kaolin Clay", "Hyaluronic Acid"],
      sizes: ["5-piece set"],
    },
    {
      id: 48,
      name: "Bridal Glow Gift Set",
      category: "gift",
      catLabel: "Gift Set",
      price: 120,
      oldPrice: 145,
      rating: 4.9,
      reviews: 41,
      badge: "sale",
      concern: "brightening",
      img: "images/photo-1612817288484-6f916006741a.webp",
      short: "A radiant pre-wedding ritual — brightening serum, eye mask and glow mist.",
      long: "Designed for the big day. This set combines our brightening serum, firming eye patches and a dewy radiance mist so brides (and grooms) arrive with a lit-from-within glow.",
      ingredients: ["Vitamin C", "Peptides", "Caffeine", "Hyaluronic Acid"],
      sizes: ["4-piece set"],
    },
    {
      id: 49,
      name: "Men's Grooming Gift Set",
      category: "gift",
      catLabel: "Gift Set",
      price: 84,
      oldPrice: 102,
      rating: 4.8,
      reviews: 67,
      badge: "sale",
      concern: "repair",
      img: "images/photo-1556228578-8c89e6adf883.webp",
      short: "A fuss-free trio — gel cleanser, SPF and repair oil for daily grooming.",
      long: "No-fuss, results-first grooming: a clarifying gel wash, invisible SPF50 and a lightweight repair oil that calms razor burn. Everything he needs, nothing he doesn't.",
      ingredients: ["Salicylic Acid", "Zinc Oxide", "Squalane", "Green Tea Extract"],
      sizes: ["3-piece set"],
    },
    {
      id: 50,
      name: "Travel Skincare Set",
      category: "gift",
      catLabel: "Gift Set",
      price: 49,
      oldPrice: 62,
      rating: 4.6,
      reviews: 143,
      badge: "sale",
      concern: "hydration",
      img: "images/photo-1767102125499-0ce314436f67.webp",
      short: "A TSA-friendly kit of cleanser, serum and moisturizer in travel sizes.",
      long: "All your essentials in carry-on-friendly sizes: mini cleanser, glow serum, moisturizer and SPF. Packed in a reusable pouch, ready for the jet-set ritual.",
      ingredients: ["Hyaluronic Acid", "Niacinamide", "Ceramides", "Aloe Vera"],
      sizes: ["4-piece set"],
    },
    {
      id: 51,
      name: "Premium Beauty Gift Box",
      category: "gift",
      catLabel: "Gift Set",
      price: 150,
      oldPrice: 185,
      rating: 4.9,
      reviews: 39,
      badge: "sale",
      concern: "brightening",
      img: "images/photo-1620916566398-39f1143ab7be.webp",
      short: "The indulgent edit — full-size bestsellers wrapped in a keepsake box.",
      long: "Our most luxurious box yet: full-size glow serum, peptide moisturizer, night balm and a silk gua sha. Beautifully wrapped in a reusable keepsake box — the gift that keeps glowing.",
      ingredients: ["Peptide Complex", "Bakuchiol", "Squalane", "Vitamin C"],
      sizes: ["6-piece set"],
    },
    {
      id: 52,
      name: "Mini Skincare Set",
      category: "gift",
      catLabel: "Gift Set",
      price: 39,
      oldPrice: 48,
      rating: 4.5,
      reviews: 176,
      badge: "sale",
      concern: "hydration",
      img: "images/photo-1620916566398-39f1143ab7be.webp",
      short: "Five pocket-sized heroes to trial the Stackly ritual on a budget.",
      long: "The perfect starter or stocking stuffer: five mini sizes of our most-loved cleanser, serum, moisturizer, SPF and facial oil. Generous enough to truly trial, small enough to gift.",
      ingredients: ["Hyaluronic Acid", "Rosehip Oil", "Zinc Oxide", "Ceramides"],
      sizes: ["Mini set"],
    },
    {
      id: 53,
      name: "Festive Gift Set",
      category: "gift",
      catLabel: "Gift Set",
      price: 99,
      oldPrice: 125,
      rating: 4.8,
      reviews: 64,
      badge: "sale",
      concern: "hydration",
      img: "images/photo-1596462502278-27bfdc403348.webp",
      short: "A holiday-ready box of glow essentials with gift-wrap included.",
      long: "Season's greetings, bottled. The Festive Gift Set pairs our glow serum, hydra cream and sheet mask duo with festive recycled wrapping and a handwritten-style gift card slot.",
      ingredients: ["Vitamin C", "Hyaluronic Acid", "Ceramides", "Matcha Extract"],
      sizes: ["4-piece set"],
    },
    {
      id: 54,
      name: "Body Care Gift Set",
      category: "gift",
      catLabel: "Gift Set",
      price: 58,
      oldPrice: 70,
      rating: 4.7,
      reviews: 88,
      badge: "sale",
      concern: "hydration",
      img: "images/photo-1775989982439-610be22c8c7b.webp",
      short: "Body butter, cleansing milk and dry-touch oil for head-to-toe softness.",
      long: "A head-to-toe treat: whipped body butter, creamy cleansing milk and a fast-absorbing dry-touch body oil. Skin stays soft, scented and satiny for 48 hours.",
      ingredients: ["Shea Butter", "Cocoa Butter", "Squalane", "Oat Milk"],
      sizes: ["3-piece set"],
    },
    {
      id: 55,
      name: "Couple's Skincare Set",
      category: "gift",
      catLabel: "Gift Set",
      price: 135,
      oldPrice: 168,
      rating: 4.9,
      reviews: 35,
      badge: "sale",
      concern: "repair",
      img: "images/photo-1512290923902-8a9f81dc236c.webp",
      short: "Two matching routines — one box made for shared self-care evenings.",
      long: "Double the glow, double the fun. This box includes two full routines (cleanser, serum and moisturizer for each) plus a shared sheet-mask duo for matching spa nights.",
      ingredients: ["Hyaluronic Acid", "Niacinamide", "Ceramides", "Squalane"],
      sizes: ["8-piece set"],
    },
    {
      id: 56,
      name: "New Customer Starter Kit",
      category: "gift",
      catLabel: "Gift Set",
      price: 29,
      oldPrice: 40,
      rating: 4.6,
      reviews: 210,
      badge: "sale",
      concern: "hydration",
      img: "images/photo-1768235146551-2a438a81aea2.webp",
      short: "An affordable four-step kit to discover your new clean-beauty ritual.",
      long: "Everything you need to begin: gentle cleanser, hydra toner, glow serum and SPF in friendly travel sizes. The lowest-commitment way to fall in love with Stackly.",
      ingredients: ["Hyaluronic Acid", "Green Tea Extract", "Zinc Oxide", "Panthenol"],
      sizes: ["4-piece set"],
    },
    {
      id: 57,
      name: "Complete Skincare Gift Box",
      category: "gift",
      catLabel: "Gift Set",
      price: 180,
      oldPrice: 220,
      rating: 5.0,
      reviews: 28,
      badge: "sale",
      concern: "brightening",
      img: "images/photo-1616394584738-fc6e612e71b9.webp",
      short: "The full Stackly ritual — every step, every hero product, one complete box.",
      long: "Our definitive collection: cleanser, toner, essence, serum, eye cream, moisturizer, facial oil and SPF — the complete 8-step ritual, beautifully boxed and gift-ready.",
      ingredients: ["Vitamin C", "Peptides", "Ceramides", "Bakuchiol"],
      sizes: ["8-piece set"],
    },
  ];

  const CATEGORIES = [
    { key: "all", label: "All Products" },
    { key: "serum", label: "Serums" },
    { key: "moisturizer", label: "Moisturizers" },
    { key: "oil", label: "Facial Oils" },
    { key: "sun", label: "Sun Care" },
    { key: "cleanser", label: "Cleansers" },
    { key: "toner", label: "Toners" },
    { key: "mask", label: "Masks" },
    { key: "eye", label: "Eye Care" },
    { key: "tool", label: "Tools" },
    { key: "gift", label: "Gift Sets" },
  ];

  function money(n) {
    return "$" + n.toFixed(2);
  }

  function stars(rating) {
    return '<i class="bi bi-star-fill"></i> ' + rating.toFixed(1);
  }

  function badgeHtml(p) {
    if (!p.badge) return "";
    const map = { new: "New", hot: "Bestseller", sale: "-" + Math.round((1 - p.price / p.oldPrice) * 100) + "%" };
    const cls = { new: "badge-new", hot: "badge-hot", sale: "badge-sale" }[p.badge];
    return '<span class="badge ' + cls + '">' + map[p.badge] + "</span>";
  }

  function productCard(p, opts) {
    opts = opts || {};
    var title = opts.noNameLink
      ? '<h3 class="product-title">' + p.name + "</h3>"
      : '<h3><a class="product-title" href="product.html?id=' + p.id + '">' + p.name + "</a></h3>";
    return (
      '<div class="product-card-wrap">' +
      '<article class="product-card" data-id="' + p.id + '">' +
        '<div class="product-media">' +
          '<a href="product.html?id=' + p.id + '" aria-label="View ' + p.name + '">' +
            '<img src="' + p.img + '" alt="' + p.name + '" loading="lazy" />' +
          "</a>" +
          badgeHtml(p) +
          '<button class="wishlist" aria-label="Add to wishlist"><i class="bi bi-heart"></i></button>' +
          '<div class="product-actions">' +
            '<button class="add-cart" data-name="' + p.name + '" data-price="' + p.price + '"><i class="bi bi-bag-plus"></i> Add to Bag</button>' +
            (opts.noBuyNow ? "" : '<button class="buy-now" data-name="' + p.name + '" data-price="' + p.price + '"><i class="bi bi-lightning-charge"></i> Buy Now</button>') +
          "</div>" +
        "</div>" +
        '<div class="product-info">' +
          '<span class="product-cat">' + p.catLabel + "</span>" +
          title +
          '<div class="product-rating">' + stars(p.rating) + " <span>(" + p.reviews + ")</span></div>" +
          '<div class="product-foot">' +
            '<strong class="price">' + money(p.price) + "</strong>" +
            (p.oldPrice ? '<span class="price-old">' + money(p.oldPrice) + "</span>" : "") +
          "</div>" +
        "</div>" +
      "</article>" +
      "</div>"
    );
  }

  window.ECLAT = window.ECLAT || {};
  window.ECLAT.PRODUCTS = PRODUCTS;
  window.ECLAT.CATEGORIES = CATEGORIES;
  window.ECLAT.money = money;
  window.ECLAT.productCard = productCard;

})();
